name: Publish Chrome Extension

on:
  push:
    tags:
      - 'V*'

jobs:
  build:
    name: Publish Chrome Extension
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - uses: pnpm/action-setup@v4
      with:
        version: latest
        
    - uses: actions/setup-node@v4
      with:
        node-version: '>=18.17.0'
        cache: 'pnpm'
    
    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Format check
      run: pnpm run format-check

    - name: Build and Zip
      run: pnpm run zip
      
    - name: Upload & Release
      uses: mnao305/chrome-extension-upload@v5.0.0
      with:
        file-path: package/github-issue-glance.zip
        extension-id: ${{ secrets.EXTENSION_ID }}
        client-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        refresh-token: ${{ secrets.REFRESH_TOKEN }}